version: "3.8"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "jenkins-home:/var/jenkins_home"
volumes:
  jenkins-home: {}